// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-Fmjqp2ICOXIbLd5l8VU6VXN8Ugpa8Mg',
    appId: '1:652833418777:web:ad4f348d9c37ea045a4488',
    messagingSenderId: '652833418777',
    projectId: 'subpay-9514c',
    authDomain: 'subpay-9514c.firebaseapp.com',
    storageBucket: 'subpay-9514c.firebasestorage.app',
    measurementId: 'G-59MPEJHQ79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC26qSakV7S6nXnqBfo_5bffqqtFcvvH2o',
    appId: '1:652833418777:android:e02941edcf0b4d5f5a4488',
    messagingSenderId: '652833418777',
    projectId: 'subpay-9514c',
    storageBucket: 'subpay-9514c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjXZz-EITz6Z1IfENnZLFz5Sydhw1zjhQ',
    appId: '1:652833418777:ios:d8761394530c9d075a4488',
    messagingSenderId: '652833418777',
    projectId: 'subpay-9514c',
    storageBucket: 'subpay-9514c.firebasestorage.app',
    iosBundleId: 'com.mohkar.subpay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjXZz-EITz6Z1IfENnZLFz5Sydhw1zjhQ',
    appId: '1:652833418777:ios:d8761394530c9d075a4488',
    messagingSenderId: '652833418777',
    projectId: 'subpay-9514c',
    storageBucket: 'subpay-9514c.firebasestorage.app',
    iosBundleId: 'com.mohkar.subpay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-Fmjqp2ICOXIbLd5l8VU6VXN8Ugpa8Mg',
    appId: '1:652833418777:web:6d0e3fb98bbbf6875a4488',
    messagingSenderId: '652833418777',
    projectId: 'subpay-9514c',
    authDomain: 'subpay-9514c.firebaseapp.com',
    storageBucket: 'subpay-9514c.firebasestorage.app',
    measurementId: 'G-6DM2NFGD0T',
  );
}
